version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "10:00"
    # only open PRs for security updates
    open-pull-requests-limit: 0
    rebase-strategy: disabled
